service: arduino-radiator-backend

provider:
  name: aws
  apiKeys:
    - arduino-radiator
  runtime: python3.6

  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "logs:*"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "cloudwatch:describe*"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "codepipeline:list*"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "codepipeline:get*"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "codecommit:get*"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "cloudwatch:GetMetricStatistics"
      Resource: "*"

functions:
  status:
    handler: handler.status
    timeout: 30
    memorySize: 256
    environment:
      gitlabToken: nrYiHY5xaPUjh3o7pM7z
    events:
      - http:
          path: status
          method: get
          private: true
plugins:
  - serverless-python-requirements
package:
  exclude:
    - a/** # virtualenv